# Enable GPIO driver subsystem framework
CONFIG_GPIO=y

# Added automatically by Workbench for Zephyr
#--- DEBUG PRESET - BEGIN ---#
# Set to -Og
CONFIG_DEBUG_OPTIMIZATIONS=y
# Thread awareness support
CONFIG_DEBUG_THREAD_INFO=y
# Generate stack usage per-function
CONFIG_STACK_USAGE=y
# Other options in case not set by default
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_BUILD_OUTPUT_META=y
CONFIG_OUTPUT_SYMBOLS=y
CONFIG_OUTPUT_STAT=y
CONFIG_OUTPUT_DISASSEMBLY=y
CONFIG_OUTPUT_PRINT_MEMORY_USAGE=y
#--- DEBUG PRESET - END ---#

#--- APPLICATION COFIGURATION ---#
# Enables the custom LED subsystem defined in your Kconfig
CONFIG_APP_LED_SUBSYSTEM=y
# Sets the blinking heartbeat interval (matches your Kconfig range constraints)
CONFIG_APP_HEARTBEAT_PERIOD_MS=500

#--- LOG ROUTING TO RTT VIEWER ---#
# Disable standard UART console
CONFIG_UART_CONSOLE=n

# Enable SEGGER RTT Console
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
