CONFIG_GPIO=y
CONFIG_LOG=y

######################## Added the lines below lines to route logs to RTT VIEWER #################################################
# Route logs through SEGGER RTT instead of UART
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_LOG_BACKEND_RTT=y

# (Optional) Disable the UART console to prevent conflicts
CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_UART=n

# (Optional) Deliver logs immediately rather than buffering them
CONFIG_LOG_MODE_IMMEDIATE=y